export const types = {
  main: {
    loadGenres: "[MAIN] Load genres",
    loadPlatforms: "[MAIN] Load platforms",
    loadGames: "[MAIN] Load games",
    setEditGame: "[MAIN] Set edit game",
    clearArrays: "[MAIN] Clear arrays",
    changeSearchName: "[MAIN] Change search name",
    changeOrderSense: "[MAIN] Change order sense",
    changeOrderBy: "[MAIN] Change order by",
    changeFilterSource: "[MAIN] Change filter source",
    changeFilterGenre: "[MAIN] Change filter genre",
    setActiveButton: "[MAIN] Set active button",
    enableNextButton: "[MAIN] Enable next button",
    disableNextButton: "[MAIN] Disable next button",
    enableBackButton: "[MAIN] Enable back button",
    disableBackButton: "[MAIN] Disable back button",
    setTotalButtons: "[MAIN] Set total buttons",
    loadRendererGames: "[MAIN] Load renderer games",
    setDetailedGame: "[MAIN] Set detailed game",
    resetDetailedGame: "[MAIN] Reset detailed game",
    changeInputValue: "[MAIN] Change input value",
    setTemporaryImage: "[MAIN] Set temporay image",
    resetTemporaryImage: "[MAIN] Reset temporay image",
    addGameToRenderList: "[MAIN] Add game to render list",
    updateGameFromRenderList: "[MAIN] Update game from render list",
    setCurrentScreen: "[MAIN] Set current screen",
    updateDeletedGame: "[MAIN] Update deleted game",
    setGoSearch: "[MAIN] Set go search",
    resetGoSearch: "[MAIN] Reset go search",
  },

  components: {
    loadGenresNames: "[COMP] Load genres names",
    loadPlatformsNames: "[COMP] Load platforms names",
    setSelectedOption: "[COMP] Set selected option",
    showListbox: "[COMP] Show listbox",
    hideListbox: "[COMP] Hide listbox",
    showRatingPicker: "[COMP] Show rating picker",
    hideRatingPicker: "[COMP] Hide rating picker",
    showDatePicker: "[COMP] Show date picker",
    hideDatePicker: "[COMP] Hide date picker",
  },

  ui: {
    startLoading: "[UI] Start loading",
    finishLoading: "[UI] Finish loading",
    setError: "[UI] Set error",
    removeError: "[UI] Remove error",
  },
};
