export const types = {
  main: {
    // loadGenres: "[MAIN] Load genres",
    // loadPlatforms: "[MAIN] Load platforms",
    loadPlatformsGenres: "[MAIN] Load platforms genres",
    loadGames: "[MAIN] Load games",
    setEditGame: "[MAIN] Set edit game",
    clearArrays: "[MAIN] Clear arrays",
    changeSearchName: "[MAIN] Change search name",
    changeOrderSense: "[MAIN] Change order sense",
    changeOrderBy: "[MAIN] Change order by",
    changeFilterSource: "[MAIN] Change filter source",
    changeFilterGenre: "[MAIN] Change filter genre",
    loadRendererGames: "[MAIN] Load renderer games",
    setDetailedGame: "[MAIN] Set detailed game",
    resetDetailedGame: "[MAIN] Reset detailed game",
    changeInputValue: "[MAIN] Change input value",
    setTemporaryImage: "[MAIN] Set temporay image",
    resetTemporaryImage: "[MAIN] Reset temporay image",
    addGameToRenderList: "[MAIN] Add game to render list",
    updateGameFromRenderList: "[MAIN] Update game from render list",
    setCurrentScreen: "[MAIN] Set current screen",
    updateDeletedGame: "[MAIN] Update deleted game",
    setGoSearch: "[MAIN] Set go search",
    resetGoSearch: "[MAIN] Reset go search",
    setSavingGameFlag: "[MAIN] Set saving game flag",
    resetSavingGameFlag: "[MAIN] Reset saving game flag",
  },

  games: {
    cleanArrays: "[GAMES] Clean arrays",
    loadArray: "[GAMES] Load array",
    loadNextPage: "[GAMES] Load next page",
    enableSavingGameFlag: "[GAMES] Enable saving game flag",
    disableSavingGameFlag: "[GAMES] Disable saving game flag",
    loadRendererGames: "[GAMES] Load renderer games",
    changeOrderSense: "[GAMES] Change order sense",
    changeOrderBy: "[GAMES] Change order by",
    changeFilterSource: "[GAMES] Change filter source",
    changeFilterGenre: "[GAMES] Change filter genre",
    changeInputValue: "[GAMES] Change input value",
    setTemporaryImage: "[GAMES] Set temporay image",
    resetTemporaryImage: "[GAMES] Reset temporay image",
    setCurrentScreen: "[GAMES] Set current screen",
    changeSearchName: "[GAMES] Change search name",
    setGoSearch: "[GAMES] Set go search",
    resetGoSearch: "[GAMES] Reset go search",
    setNewGame: "[GAMES] Set new game",
  },

  components: {
    loadGenresNames: "[COMP] Load genres names",
    loadPlatformsNames: "[COMP] Load platforms names",
    setSelectedOption: "[COMP] Set selected option",
    showListbox: "[COMP] Show listbox",
    hideListbox: "[COMP] Hide listbox",
    listboxParent: "[COMP] Listbox parent",
    showRatingPicker: "[COMP] Show rating picker",
    hideRatingPicker: "[COMP] Hide rating picker",
    showDatePicker: "[COMP] Show date picker",
    hideDatePicker: "[COMP] Hide date picker",
    resetListboxValues: "[COMP] Reset listbox values",
  },

  ui: {
    startLoading: "[UI] Start loading",
    finishLoading: "[UI] Finish loading",
    setError: "[UI] Set error",
    removeError: "[UI] Remove error",
  },
};
